#!/bin/bash

GUM=$(echo -e "Add\nCommit\n" | gum filter)

function repoExists() {
  if [[ ! -d .git ]]; then
    echo "Not a git repository"
    exit 1
  fi
}

function _add() {
  repoExists
  gum confirm "Only 'git add .' is supported for now, continue ? : " && git add .
  exit 0
}

function _commit() {
  repoExists
  GIT_MSG_TITLE=$(gum input --placeholder "Title ")
  GIT_MSG_DESC=$(gum write --width 70 --placeholder "Describe the commit (CTRL+D to finish)")
  # Check if  $GIT_MSG_TITLE is empty and if so, set to the actual date
  if [[ -z $GIT_MSG_TITLE ]]; then
    GIT_MSG_TITLE="Commit from $(date)"
  fi
  echo "You did not entered a title, the commit will be named 'Commit from $(date)'"
  git commit -m "$GIT_MSG_TITLE" -m "$GIT_MSG_DESC"
  exit 0
}

# Check if the user selected a commit or push but check if a .git folder exists
if [[ $GUM == "Commit" ]]; then
  _commit
elif [[ $GUM == "Add" ]]; then
  _add
fi
